# Generated by Django 3.1.2 on 2020-10-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aim',
            new_name='Cel',
        ),
    ]
