# Generated by Django 3.1.2 on 2020-10-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_auto_20201003_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cel',
            new_name='Aim',
        ),
        migrations.RenameField(
            model_name='aim',
            old_name='cel',
            new_name='aim',
        ),
        migrations.RenameField(
            model_name='aim',
            old_name='kwota',
            new_name='price',
        ),
    ]
